---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false # Temporary disable due to current nonsupport of eslint2.x
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/**
- docs/**